package guiFrames;

import ActionPacks.teamNameReader;
import ActionPacks.teamNameWriter;
import ActionPacks.teamReader;
import ActionPacks.teamWriter;
import Objects.TeamObject;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jonathanleitschuh
 */
public class editTeamsFrame extends javax.swing.JFrame {
    private String idNumB;
    private int idNumbeR;
    private String teamNumbeR;
    private String teamLetteR;
    private String teamNamE;
    private String locatioN;
    private String robotNamE;
    private String comment;

    /**
     * Creates new form editTeamsFrame
     */
    public editTeamsFrame(String NUMBER, String LETTER) throws ClassNotFoundException {
        teamReader READ = new teamReader();
        TeamObject read = (TeamObject)READ.readTeamObject(NUMBER, LETTER);
        idNumB = read.getId();
        //idNumbeR = read.getIdNumber();
        teamNumbeR = read.getTeamNumb();
        teamLetteR = read.getTeamLetter();
        teamNamE = read.getTeamName();
        locatioN = read.getLocation();
        robotNamE = read.getRobotName();
        comment = read.getTeamComment();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButton = new javax.swing.JButton();
        editTeamPreferences = new javax.swing.JPanel();
        teamNameLabel = new javax.swing.JLabel();
        teamName = new javax.swing.JTextField();
        teamNumberLabel = new javax.swing.JLabel();
        teamNumber = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        robotNameLabel = new javax.swing.JLabel();
        robotName = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        teamLetterLabel = new javax.swing.JLabel();
        teamLetter = new javax.swing.JTextField();
        javax.swing.JButton saveCloseButton = new javax.swing.JButton();
        commentPannel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VEX Alliance Selection App");
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        backButton.setText("<< Back");
        backButton.setToolTipText("Return to main screen.");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        getContentPane().add(backButton, gridBagConstraints);

        editTeamPreferences.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Team Preferences"));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        editTeamPreferences.setLayout(jPanel2Layout);

        teamNameLabel.setText("Team Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        editTeamPreferences.add(teamNameLabel, gridBagConstraints);

        teamName.setText(teamNamE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 150;
        editTeamPreferences.add(teamName, gridBagConstraints);

        teamNumberLabel.setText("Team Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        editTeamPreferences.add(teamNumberLabel, gridBagConstraints);

        teamNumber.setText(teamNumbeR);
        teamNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        editTeamPreferences.add(teamNumber, gridBagConstraints);

        locationLabel.setText("Location:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        editTeamPreferences.add(locationLabel, gridBagConstraints);

        robotNameLabel.setText("Robot Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        editTeamPreferences.add(robotNameLabel, gridBagConstraints);

        robotName.setText(robotNamE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        editTeamPreferences.add(robotName, gridBagConstraints);

        location.setText(locatioN);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        editTeamPreferences.add(location, gridBagConstraints);

        teamLetterLabel.setLabelFor(teamLetter);
        teamLetterLabel.setText("Team Letter:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        editTeamPreferences.add(teamLetterLabel, gridBagConstraints);

        teamLetter.setText(teamLetteR);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 12;
        editTeamPreferences.add(teamLetter, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(editTeamPreferences, gridBagConstraints);

        saveCloseButton.setText("Save and Close");
        saveCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCloseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(saveCloseButton, gridBagConstraints);

        commentPannel.setBorder(javax.swing.BorderFactory.createTitledBorder("Comments"));
        commentPannel.setLayout(new java.awt.GridBagLayout());

        commentBox.setColumns(20);
        commentBox.setRows(5);
        commentBox.setText(comment);
        jScrollPane2.setViewportView(commentBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 550;
        gridBagConstraints.ipady = 100;
        commentPannel.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(commentPannel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNumberActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        teamsListFrame teams = new teamsListFrame();
        teams.setSize(this.getWidth(), getHeight());
        teams.setLocation(this.getX(), this.getY());
        teams.setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCloseButtonActionPerformed
        // TODO add your handling code here:
         try {
            if (Double.parseDouble(this.teamNumber.getText()) > 0) {
                
                TeamObject team = new TeamObject();
                team.setId(this.idNumB);
                
                team.setTeamName(teamName.getText());
                
                team.setTeamNumber(teamNumber.getText());
                team.setTeamLetter(teamLetter.getText().toUpperCase()); //Sets the letter to upper case automatically
                team.setRobotName(robotName.getText());
                team.setLocation(location.getText());
                team.setTeamComment(commentBox.getText());
                
                
                // Write a new file that contains the team data
                teamWriter writer = new teamWriter();
                writer.writeTeamObject(teamNumber.getText(), teamLetter.getText(), team);
                

                // Read the Array list file
                teamNameReader read = new teamNameReader();
                ArrayList<TeamObject> READ = read.readTeamNameObject();
                
                
                // Write the Array list file back
                teamNameWriter write = new teamNameWriter();
                write.writeOldTeamObject(idNumB, teamName.getText(), teamNumber.getText(), 
                        teamLetter.getText().toUpperCase(), robotName.getText(), location.getText(), commentBox.getText(), READ);
                

                // Close the window here.
                teamsListFrame teams = new teamsListFrame();
                teams.setSize(this.getWidth(), getHeight());
                teams.setLocation(this.getX(), this.getY());
                teams.setVisible(true);
                this.dispose();
            }

        } catch (Exception e) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(this, "Invalid Entry" + "\n Please check your entries.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editTeamsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editTeamsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editTeamsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editTeamsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea commentBox;
    private javax.swing.JPanel commentPannel;
    private javax.swing.JPanel editTeamPreferences;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField location;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField robotName;
    private javax.swing.JLabel robotNameLabel;
    private javax.swing.JTextField teamLetter;
    private javax.swing.JLabel teamLetterLabel;
    private javax.swing.JTextField teamName;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JTextField teamNumber;
    private javax.swing.JLabel teamNumberLabel;
    // End of variables declaration//GEN-END:variables
}
