/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiFrames;

import Objects.MatchObject;

/**
 *
 * @author jonathanleitschuh
 */
public class MatchTeamFrame extends javax.swing.JFrame {

    /**
     * Creates new form MatchTeamFrame
     */
    public MatchTeamFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        teams = new javax.swing.JPanel();
        red = new javax.swing.JPanel();
        oneR = new guiFrames.MatchTeamSubFrame();
        twoR = new guiFrames.MatchTeamSubFrame();
        redTeamScoreLabel = new javax.swing.JLabel();
        redTeamScore = new javax.swing.JTextField();
        blue = new javax.swing.JPanel();
        oneB = new guiFrames.MatchTeamSubFrame();
        twoB = new guiFrames.MatchTeamSubFrame();
        blueTeamScoreLabel = new javax.swing.JLabel();
        blueTeamScore = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();
        saveAndCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        teams.setBorder(javax.swing.BorderFactory.createTitledBorder("Match Info"));
        java.awt.GridBagLayout teamsLayout = new java.awt.GridBagLayout();
        teamsLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        teamsLayout.rowHeights = new int[] {0};
        teams.setLayout(teamsLayout);

        red.setBorder(javax.swing.BorderFactory.createTitledBorder("Red Team:"));
        java.awt.GridBagLayout redLayout = new java.awt.GridBagLayout();
        redLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        redLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        red.setLayout(redLayout);

        oneR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        red.add(oneR, gridBagConstraints);

        twoR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        red.add(twoR, gridBagConstraints);

        redTeamScoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        redTeamScoreLabel.setText("Red Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 30;
        red.add(redTeamScoreLabel, gridBagConstraints);

        redTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        red.add(redTeamScore, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        teams.add(red, gridBagConstraints);

        blue.setBorder(javax.swing.BorderFactory.createTitledBorder("Blue Team:"));
        java.awt.GridBagLayout blueLayout = new java.awt.GridBagLayout();
        blueLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        blueLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        blue.setLayout(blueLayout);

        oneB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        blue.add(oneB, gridBagConstraints);

        twoB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        blue.add(twoB, gridBagConstraints);

        blueTeamScoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        blueTeamScoreLabel.setText("Blue Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 30;
        blue.add(blueTeamScoreLabel, gridBagConstraints);

        blueTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        blue.add(blueTeamScore, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        teams.add(blue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(teams, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jComboBox1, gridBagConstraints);

        backButton.setText("<< Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(backButton, gridBagConstraints);

        saveAndCloseButton.setText("Save and Close");
        saveAndCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndCloseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(saveAndCloseButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndCloseButtonActionPerformed
        // TODO add your handling code here:
        MatchObject match = new MatchObject();
        match.red.setScore(redTeamScore.getText());
        match.blue.setScore(blueTeamScore.getText());
        
        match.red.teamone.setPrimaryScore(oneR.primaryScorer.isSelected());
        match.red.teamtwo.setPrimaryScore(twoR.primaryScorer.isSelected());
        
        match.blue.teamone.setPrimaryScore(oneB.primaryScorer.isSelected());
        match.blue.teamtwo.setPrimaryScore(twoB.primaryScorer.isSelected());
        
        match.red.teamone.setAutonomous(oneR.autonomous.isSelected());
        match.red.teamtwo.setAutonomous(twoR.autonomous.isSelected());
        
        match.blue.teamone.setAutonomous(oneB.autonomous.isSelected());
        match.blue.teamtwo.setAutonomous(twoB.autonomous.isSelected());
        
        
    }//GEN-LAST:event_saveAndCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MatchTeamFrame frame = new MatchTeamFrame();
        frame.setVisible(true);
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel blue;
    private javax.swing.JTextField blueTeamScore;
    private javax.swing.JLabel blueTeamScoreLabel;
    private javax.swing.JComboBox jComboBox1;
    private guiFrames.MatchTeamSubFrame oneB;
    private guiFrames.MatchTeamSubFrame oneR;
    private javax.swing.JPanel red;
    private javax.swing.JTextField redTeamScore;
    private javax.swing.JLabel redTeamScoreLabel;
    private javax.swing.JButton saveAndCloseButton;
    private javax.swing.JPanel teams;
    private guiFrames.MatchTeamSubFrame twoB;
    private guiFrames.MatchTeamSubFrame twoR;
    // End of variables declaration//GEN-END:variables
}
