/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiFrames;

/**
 *
 * @author jonathanleitschuh
 */
public class MatchTeamSubFrame extends javax.swing.JPanel {

    /**
     * Creates new form MatchTeamSubFrame
     */
    public MatchTeamSubFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        teamSelectionPanel = new javax.swing.JPanel();
        teamSelectionBox = new javax.swing.JComboBox();
        problemsPanel = new javax.swing.JPanel();
        badRobot = new javax.swing.JCheckBox();
        batteryFail = new javax.swing.JCheckBox();
        vexNetFail = new javax.swing.JCheckBox();
        matchMissed = new javax.swing.JCheckBox();
        autonomousPanel = new javax.swing.JPanel();
        autonomous = new javax.swing.JCheckBox();
        autonomousScoreLabel = new javax.swing.JLabel();
        autonomousScore = new javax.swing.JTextField();
        primaryScorer = new javax.swing.JCheckBox();
        commentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextPane();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        teamSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Team:"));
        teamSelectionPanel.setLayout(new java.awt.GridBagLayout());

        teamSelectionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        teamSelectionPanel.add(teamSelectionBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 100;
        add(teamSelectionPanel, gridBagConstraints);

        problemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Problems:"));
        java.awt.GridBagLayout problemsLayout = new java.awt.GridBagLayout();
        problemsLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        problemsLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        problemsPanel.setLayout(problemsLayout);

        badRobot.setText("Bad Robot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        problemsPanel.add(badRobot, gridBagConstraints);

        batteryFail.setText("Battery Fail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        problemsPanel.add(batteryFail, gridBagConstraints);

        vexNetFail.setText("VEX Net Fail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        problemsPanel.add(vexNetFail, gridBagConstraints);

        matchMissed.setText("Missed Match");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        problemsPanel.add(matchMissed, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(problemsPanel, gridBagConstraints);

        autonomousPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Qualities:"));
        autonomousPanel.setLayout(new java.awt.GridBagLayout());

        autonomous.setText("Autonomous");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        autonomousPanel.add(autonomous, gridBagConstraints);

        autonomousScoreLabel.setText("Autonomous Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        autonomousPanel.add(autonomousScoreLabel, gridBagConstraints);

        autonomousScore.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        autonomousPanel.add(autonomousScore, gridBagConstraints);

        primaryScorer.setText("Primary Scorer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        autonomousPanel.add(primaryScorer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(autonomousPanel, gridBagConstraints);

        commentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Comments:"));
        commentPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportView(comment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        commentPanel.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 50;
        add(commentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox autonomous;
    private javax.swing.JPanel autonomousPanel;
    public javax.swing.JTextField autonomousScore;
    private javax.swing.JLabel autonomousScoreLabel;
    public javax.swing.JCheckBox badRobot;
    public javax.swing.JCheckBox batteryFail;
    public javax.swing.JTextPane comment;
    private javax.swing.JPanel commentPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JCheckBox matchMissed;
    public javax.swing.JCheckBox primaryScorer;
    private javax.swing.JPanel problemsPanel;
    private javax.swing.JComboBox teamSelectionBox;
    private javax.swing.JPanel teamSelectionPanel;
    public javax.swing.JCheckBox vexNetFail;
    // End of variables declaration//GEN-END:variables
}
