/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiFrames;
import ActionPacks.matchWriter;
import Objects.MatchObject;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jonathanleitschuh
 */
public class MatchTeamFrame extends javax.swing.JFrame {
    private int matchNumber;

    public int getMatchNumber() {
        return matchNumber;
    }

    public void setMatchNumber(int matchNumber) {
        this.matchNumber = matchNumber;
    }
    
    /**
     * Creates new form MatchTeamFrame
     */
    public MatchTeamFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        teams = new javax.swing.JPanel();
        red = new javax.swing.JPanel();
        redTeamScoreLabel = new javax.swing.JLabel();
        redTeamScore = new javax.swing.JTextField();
        redIsolation =  new MatchTeamSubFrame();
        redInteraction = new MatchTeamSubFrame();
        blue = new javax.swing.JPanel();
        blueTeamScoreLabel = new javax.swing.JLabel();
        blueTeamScore = new javax.swing.JTextField();
        blueIsolation = new MatchTeamSubFrame();
        blueInteraction = new MatchTeamSubFrame();
        backButton = new javax.swing.JButton();
        saveAndCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(444, 227));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        teams.setBorder(javax.swing.BorderFactory.createTitledBorder("Match Info"));
        java.awt.GridBagLayout teamsLayout = new java.awt.GridBagLayout();
        teamsLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        teamsLayout.rowHeights = new int[] {0};
        teams.setLayout(teamsLayout);

        red.setBorder(javax.swing.BorderFactory.createTitledBorder("Red Team:"));
        java.awt.GridBagLayout redLayout = new java.awt.GridBagLayout();
        redLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        redLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        red.setLayout(redLayout);

        redTeamScoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        redTeamScoreLabel.setText("Red Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 30;
        red.add(redTeamScoreLabel, gridBagConstraints);

        redTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        red.add(redTeamScore, gridBagConstraints);

        redIsolation.setBorder(javax.swing.BorderFactory.createTitledBorder("Isolation"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        red.add(redIsolation, gridBagConstraints);

        redInteraction.setBorder(javax.swing.BorderFactory.createTitledBorder("Interaction"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        red.add(redInteraction, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        teams.add(red, gridBagConstraints);

        blue.setBorder(javax.swing.BorderFactory.createTitledBorder("Blue Team:"));
        java.awt.GridBagLayout blueLayout = new java.awt.GridBagLayout();
        blueLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        blueLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        blue.setLayout(blueLayout);

        blueTeamScoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        blueTeamScoreLabel.setText("Blue Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 30;
        blue.add(blueTeamScoreLabel, gridBagConstraints);

        blueTeamScore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        blue.add(blueTeamScore, gridBagConstraints);

        blueIsolation.setBorder(javax.swing.BorderFactory.createTitledBorder("Isolation"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        blue.add(blueIsolation, gridBagConstraints);

        blueInteraction.setBorder(javax.swing.BorderFactory.createTitledBorder("Interaction"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        blue.add(blueInteraction, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        teams.add(blue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(teams, gridBagConstraints);

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(backButton, gridBagConstraints);

        saveAndCloseButton.setText("Save and Close");
        saveAndCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndCloseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(saveAndCloseButton, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndCloseButtonActionPerformed
        // TODO add your handling code here:
        MatchObject match = new MatchObject();
        
        
        
        MatchTeamSubFrame redIso = (MatchTeamSubFrame)redIsolation;       
        match.red.isolation.setMatchTeamObject(redIso.getMatchTeam());
        
        MatchTeamSubFrame redInter = (MatchTeamSubFrame)redInteraction;       
        match.red.interaction.setMatchTeamObject(redInter.getMatchTeam());
        
        MatchTeamSubFrame blueIso = (MatchTeamSubFrame)blueIsolation;       
        match.blue.isolation.setMatchTeamObject(blueIso.getMatchTeam());
        
        MatchTeamSubFrame blueInter = (MatchTeamSubFrame)blueInteraction;       
        match.blue.interaction.setMatchTeamObject(blueInter.getMatchTeam());
        
        match.red.setScore(Integer.parseInt(redTeamScore.getText()));
        match.blue.setScore(Integer.parseInt(blueTeamScore.getText()));
        
        match.setMatchNumber(matchNumber);
        
        matchWriter write = new matchWriter();
        try {
            write.writeMatchObjectSimple(match);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MatchTeamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        matchListFrame frame = new matchListFrame();
        frame.setSize(this.getWidth(), getHeight());
        frame.setLocation(this.getX(), this.getY());
        frame.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_saveAndCloseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        matchListFrame frame = new matchListFrame();
        frame.setSize(this.getWidth(), getHeight());
        frame.setLocation(this.getX(), this.getY());
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MatchTeamFrame frame = new MatchTeamFrame();
        frame.setVisible(true);
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel blue;
    private javax.swing.JPanel blueInteraction;
    private javax.swing.JPanel blueIsolation;
    private javax.swing.JTextField blueTeamScore;
    private javax.swing.JLabel blueTeamScoreLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel red;
    private javax.swing.JPanel redInteraction;
    private javax.swing.JPanel redIsolation;
    private javax.swing.JTextField redTeamScore;
    private javax.swing.JLabel redTeamScoreLabel;
    private javax.swing.JButton saveAndCloseButton;
    private javax.swing.JPanel teams;
    // End of variables declaration//GEN-END:variables
}
